### ISSUE TITLE
dag-factory PythonOperator 

### ISSUE THREAD

**Issue by arnekaiser-bt** [ajbosco/dag-factory#13]
Hi Adam,
I try to use the pythonoperator with the dagfactory, I tried to define a function within the python file and call this function as python_callable and get always the following error message:

`make sure config is properly populated. err:Failed to create <class 'airflow.operators.python_operator.PythonOperator'> task. err: `python_callable` param must be callable `

As long as I write the task directly within the python file its no problem to call the function.
Am I doing something wrong or is it not possible to use the pythonoperator this way?

DAG file:
```
from airflow import DAG
import dagfactory
dag_factory = dagfactory.DagFactory("/path/to/dags/config_file.yml")
dag_factory.generate_dags(globals())

# [START howto_operator_python]
def print_context(ds, **kwargs):
    pprint(kwargs)
    print(ds)
    return 'Whatever you return gets printed in the logs'

```

YAML config:

```
Python_Test:
  default_args:
    owner: 'user'
    start_date: 2019-05-28
  description: 'this is an sample dag which runs every day'
  tasks:
    test_1:
      operator: airflow.operators.python_operator.PythonOperator
      task_id: 'pythonoperator_Testtask'
      python_callable: print_context
```
