### ISSUE TITLE
Json variables not converted.

### ISSUE THREAD

**Issue by Bennyelg** [ajbosco/dag-factory#140]
dag-factory = "^0.15.0"
I tried everything, no success.
I saw the source code, indeed no reference for anything associated with variables parameters.
```yml
...
    OPP:
      operator: xxx_operators.xxx.OPP
      name: job_post_classifier
      virtual_cluster_id: '{{ var.value.virtual_cluster_id }}'
      execution_role_arn: '{{ var.value.execution_role_arn }}'
      task_image: '{{var.json.xxx_job_post.classification.image}}'
      entry_point: '{{ var.json.xxx_job_post.classification.entry_point }}'
      executor_instances: '{{ var.json.xxx_job_post.classification.executor_instances }}'
      executor_cores: '{{ var.json.xxx_job_post.classification.executor_cores }}'
      driver_cores: '{{ var.json.xxx_job_post.classification.executor_instances }}'
      executor_memory: '{{var.json.xxx_job_post.classification.executor_memory }}'
      driver_memory: '{{ var.json.xxx_job_post.classification.driver_memory }}'
...
```
<img width="949" alt="image" src="https://user-images.githubusercontent.com/9398172/193474838-2d038c29-b263-4f80-b0cb-23746b47b4a3.png">
