### ISSUE TITLE
Does dag-factory support TriggerDagOperator ?

### ISSUE THREAD

**Issue by mohamedaminch** [ajbosco/dag-factory#142]
does df support triggerdagoperator like that :

trigger_keymaps:
      operator: airflow.operators.trigger_dagrun.TriggerDagRunOperator
      trigger_dag_id: keymaps

how should I add a conf dict to that ?

**Comment by vanducng** [comment]
Like this, i believe:
```
operator: airflow.operators.trigger_dagrun.TriggerDagRunOperator
trigger_dag_id: 
  - key1: value1
  - key2: value2
  ```
