### ISSUE TITLE
Not able to set `on_failure_callback` in default args

### ISSUE THREAD

**Issue by madhavdube** [ajbosco/dag-factory#177]
I am trying to set the default args as 
```default_args={'on_failure_callback': 'foo_function_str`}```

the yaml config I am trying
```
dag_1:
   default_args:
       start_date: '1999-01-01'
       on_failure_callback: 'dags.utils.failures.send_alert' -- str representation of function
   
```

The other config I tried using `on_failure_callback_file` but this does not set the property in the default dict. 

dag factory version - 0.8.0

**Comment by subbota19** [comment]
Hi @madhavdube,

I tried creating the DAG based on your config file using the latest version of dag-factory v0.19.0, and it worked fine. Please try running it with the latest version.

As for specifying callbacks, another method is to use the parameters: _on_failure_callback_file_ and _on_failure_callback_name_. You can find more details in the [documentation](https://www.astronomer.io/docs/learn/dag-factory#step-4-optional-add-a-dag-level-callback).

One limitation is that currently it's not possible to provide callbacks within _default_args_. You can only define them at the DAG level, like this

```
dag_test:
  default_args:
    start_date: '2024-09-14'
  on_success_callback_file: "/usr/local/airflow/dags/utils/utils/failures.py"
  on_success_callback_name: "send_alert"
```
  
However, I've created a PR that will allow specifying callbacks inside _default_args_, enabling callback configurations for individual DAG tasks as well: https://github.com/astronomer/dag-factory/pull/218.
