### ISSUE TITLE
Support for SimpleHttpOperator

### ISSUE THREAD

**Issue by ayanray089** [ajbosco/dag-factory#57]
Do you support SimpleHttpOperator ?

**Comment by ilaichi** [comment]
I am able to use SimpleHttpOperator.

task_4:
      operator: airflow.providers.http.operators.http.SimpleHttpOperator
      task_id: 'get_http'
      http_conn_id: 'test-http'
      method: 'GET'
      data:
        param1: 'value1'
      headers: 
        header1: 'value1'
      log_response: true
      dependencies: [task_3]

**Comment by ilaichi** [comment]
Here is how I was able to use it.

```
task_4:
      operator: airflow.providers.http.operators.http.SimpleHttpOperator
      task_id: 'get_http'
      http_conn_id: 'test-http'
      method: 'GET'
      data:
        param1: 'value1'
      headers: 
        header1: 'value1'
      log_response: true
      dependencies: [task_3]
```
