### ISSUE TITLE
Getting rid off long imports

### ISSUE THREAD

**Issue by gardnerdev** [ajbosco/dag-factory#58]
Could we get rid off this long import?
`airflow.operators.bash_operator.BashOperator`

Would be greate to have
`BashOperator`
instead

**Comment by gigkokman** [comment]
IMHO, Explicit value makes it easy to find related information.

**Comment by guizsantos** [comment]
A workaround for this would be to import the required classes in an `utils.py` file that aggregates everything you want at the root of the dags folder. Then imports would be only from utils: `utils.BashOperator` or `utils.PythonOperator`.

You may also rename the operators or extend their functionalities, like adding more templated arguments, e.g.:

```python
# utils.py
from airflow.operators.bash_operator import BashOperator

class CustomBashOperator(BashOperator):
    template_fields = tuple(list(super().template_fields) + ["additional_templated_field"])
```

```yaml
# YAML dag factory dag
example_dag:
    owner: "airflow"
    start_date: 2022-01-01
    retries: 1
    retry_delay_sec: 300
  schedule_interval: "0 1 * * *"
  tasks:
    test:
      operator: utils.BashOperator
      bash_command: "echo 'I came from utils.py'
    test_2:
      operator: utils.CustomBashOperator
      bash_command: "echo 'I came from utils.py and I got extended'
```

**Comment by pankajkoti** [comment]
We discussed this with @pankajastro and @tatiana and we feel like we could support this ask with something like in the below interface:

Maybe extend the [defaults.yml](https://github.com/astronomer/dag-factory/blob/main/dev/dags/defaults.yml) to declare aliases for operators and dagfactory can read these aliases and apply to resolve operators from DAG yamls.
```
default_args:
  start_date: "2025-01-01"
  owner: "global_owner"

operator_aliases:
 - operator_path: airflow.operators.bash_operator.BashOperator
    operator_alias: BashOperator
 - path: airflow.operators.bash_operator.PythonOperator
    operator_alias: PythonOperator
```

and then existing yaml could leverage these:
```
default:
  default_args:
    start_date: 2024-11-11

# ----8<---   [ start: example_dag_yaml_configuration ]
basic_example_dag:
  default_args:
    owner: "custom_owner"
  description: "this is an example dag"
  schedule: "0 3 * * *"
  render_template_as_native_obj: True
  catchup: false
  task_groups:
    - group_name: "example_task_group"
      tooltip: "this is an example task group"
      dependencies: [task_1]
  tasks:
    - task_id: "task_1"
      operator: BashOperator
      bash_command: "echo 1"
    - task_id: "task_2"
      operator: PythonOperator
      ....
# ----8<---   [ end: example_dag_yaml_configuration ]
```


I have marked the issue as "good first issue" if someone in the community would like to pick this up before the Astronomer team gets a chance to work on this.
