### ISSUE TITLE
How to pass arguments to python_callable function

### ISSUE THREAD

**Issue by gayatrismt** [ajbosco/dag-factory#64]
I have method calldag(payload,dagname)... need to pass the following arguments payload and dagname. How can i pass them using yaml file

**Comment by ajbosco** [comment]
Not sure if anyone has done that yet, but they'd need to be set as the `ops_args` https://github.com/apache/airflow/blob/1.10.10/airflow/operators/python_operator.py#L81

**Comment by gayatrismt** [comment]
Yes it can be done with op_args.. how to pass that op_args in yaml file

**Comment by ajbosco** [comment]
I'm not sure where `payload` is coming in your example, but you could get the DAG name to your task using Jinja templates like this: 

```
    task_3:
      operator: airflow.operators.python_operator.PythonOperator
      python_callable_name: print_hello
      python_callable_file: /usr/local/airflow/dags/print_hello.py
      op_args:
        - '{{ dag.dag_id }}'
      op_kwargs:
        dagname: '{{ dag.dag_id }}'
```
