### ISSUE TITLE
does dagfactory support trigger_rule?

### ISSUE THREAD

**Issue by fredrick-sciera** [ajbosco/dag-factory#76]
How to pass trigger_rule in yaml file?

**Comment by SimonArnu** [comment]
This works for me:  

```
trigger_rule_test:
  default_args:
    owner: example_owner_test
    start_date: 2020-01-01T00:00:00.000Z
    retries: 0
  concurrency: 2
  max_active_runs: 1
  schedule_interval: None
  tasks:
    start:
      operator: airflow.operators.dummy_operator.DummyOperator
    failing_task:
      operator: airflow.operators.bash_operator.BashOperator
      bash_command: ls nonexistent.file
    collector_task:
      operator: airflow.operators.dummy_operator.DummyOperator
      trigger_rule: all_done
      dependencies:
        - start
        - failing_task

```
