### ISSUE TITLE
How to create a TimeSensor Task

### ISSUE THREAD

**Issue by dhodyn** [ajbosco/dag-factory#78]
The time sensor expects the target_time as a datetime.time. 

https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/sensors/time_sensor/index.html

How to add that in the yml?

**Comment by pankajastro** [comment]
yes, you can create this with latest version of dag-factory here is an example

```yaml
time_sensor_dag:
  description: TimeSensor using __type__ annotation
  schedule: "@daily"
  catchup: false

  default_args:
    owner: airflow
    start_date: "2026-01-01"

  tasks:

    wait_until_9am:
      operator: airflow.providers.standard.sensors.time.TimeSensor

      target_time:
        __type__: datetime.time
        hour: 9
        minute: 0
        second: 0
```
