### ISSUE TITLE
With airflow 2.0  passing on_failure_callback or  on_success_callback is not working 

### ISSUE THREAD

**Issue by mariamthiam** [ajbosco/dag-factory#91]
My. dag look like this : 

```
my_dag:
  schedule_interval: '@once'
  on_failure_callback_name: failure_callback
  on_failure_callback_file: /usr/local/airflow/dags/helper.py
  on_success_callback_name: success_callback
  on_success_callback_file: /usr/local/airflow/dags/helper.py

```
