### ISSUE TITLE
Support lambda in python_callable

### ISSUE THREAD

**Issue by ilaichi** [ajbosco/dag-factory#99]
Right now we need to use file and name for python callable. It should be able to take lambda as well as shown below:

```
task_2:
      operator: airflow.sensors.http_sensor.HttpSensor
      http_conn_id: 'test-http'
      method: 'GET'
      response_check_lambda: 'lambda response: "ok" in reponse.text'
      dependencies: [task_1]
```

I have been able to make it work and will raise a pull request for it.
